email: "francescogentyle@gmail.com"

plugins:
  - jekyll-seo-tag
  - jekyll-postcss
  - jekyll-sitemap

postcss:
  cache: false

title: "Eyon"

tagline: "Francesco Gentile's portfolio and blog"

description: "Francesco Gentile's portfolio and blog about software engineering. Main topics: Data and Web3"

url: "https://eyon42.github.io"

author:
  name: "Francesco Gentile"
  nickname: "Eyon"

logo: "/assets/site_logo.png"

social:
  name: Francesco Gentile
  links:
    https://www.youtube.com/channel/UCy71OIo4W_8boPSAmqrukvw
    https://github.com/Eyon42
    https://www.instagram.com/the_eyon/
    https://www.linkedin.com/in/francesco-gentile-907bb4165/
    https://www.xing.com/profile/Francesco_Gentile13/cv


google-site-verification: google34dd0bedf44b57d0.html